"""
Alert model — system alerts generated by the log analyzer.

Each alert captures an event that warrants admin attention: API failures,
quality degradation, service outages, or DB issues.

Fields
------
level:       severity — critical / warning / info
title:       short human-readable alert name
message:     detailed description of the issue
source:      service or component that triggered the alert (e.g. "anthropic", "scraper")
is_read:     whether the admin has acknowledged the alert
created_at:  UTC timestamp when the alert was created
resolved_at: UTC timestamp when the alert was resolved/dismissed (nullable)
"""

from datetime import datetime, timezone

from sqlalchemy import Boolean, Column, DateTime, Integer, String, Text

from app.database import Base


class Alert(Base):
    __tablename__ = "alerts"

    id          = Column(Integer, primary_key=True, autoincrement=True)
    level       = Column(String(20),  nullable=False, index=True)   # critical / warning / info
    title       = Column(String(200), nullable=False)
    message     = Column(Text,        nullable=False)
    source      = Column(String(100), nullable=False, index=True)
    is_read     = Column(Boolean,     nullable=False, default=False, index=True)
    created_at  = Column(
        DateTime,
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        index=True,
    )
    resolved_at = Column(DateTime, nullable=True)
