"""block-based content model

Revision ID: 85e8a19cd11a
Revises: ce375c945715
Create Date: 2026-03-11 12:02:20.979333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '85e8a19cd11a'
down_revision: Union[str, Sequence[str], None] = 'ce375c945715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.Enum('heading', 'subheading', 'paragraph', 'image', 'quote', 'bold', name='blocktype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_blocks_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_blocks_id'), ['id'], unique=False)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_image_url', sa.String(), nullable=True))

    # Preserve existing image_url data before dropping the column
    op.execute("UPDATE articles SET main_image_url = image_url WHERE main_image_url IS NULL AND image_url IS NOT NULL")

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('images')
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('images', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('main_image_url')

    with op.batch_alter_table('article_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_blocks_id'))
        batch_op.drop_index(batch_op.f('ix_article_blocks_article_id'))

    op.drop_table('article_blocks')
    # ### end Alembic commands ###
