"""add_db_indexes_articles_analytics

Revision ID: ac76c06893bc
Revises: e2f3a4b5c6d7
Create Date: 2026-06-04 11:02:45.097523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac76c06893bc'
down_revision: Union[str, Sequence[str], None] = 'e2f3a4b5c6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_site_id'), ['site_id'], unique=False)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_status'))
        batch_op.drop_index(batch_op.f('ix_articles_site_id'))

    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_site_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_created_at'))

    # ### end Alembic commands ###
