"""add alerts table

Revision ID: e2f3a4b5c6d7
Revises: c3d4e5f6a7b8
Create Date: 2026-03-17 12:00:00.000000

Adds the alerts table which stores system alerts generated by the log
analyzer worker.  Each alert records an actionable event (API failure,
quality degradation, DB error) with level, title, message, source, and
read/resolved state.

Indexes on (level), (source), (is_read), and (created_at) support the
per-level filtering and unread-count queries issued by the alerts dashboard.
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision      = 'e2f3a4b5c6d7'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on    = None


def upgrade() -> None:
    op.create_table(
        'alerts',
        sa.Column('id',          sa.Integer(),     autoincrement=True, nullable=False),
        sa.Column('level',       sa.String(20),    nullable=False),
        sa.Column('title',       sa.String(200),   nullable=False),
        sa.Column('message',     sa.Text(),         nullable=False),
        sa.Column('source',      sa.String(100),   nullable=False),
        sa.Column('is_read',     sa.Boolean(),     nullable=False, server_default='0'),
        sa.Column('created_at',  sa.DateTime(),    nullable=False),
        sa.Column('resolved_at', sa.DateTime(),    nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_alerts_level'),      'alerts', ['level'],      unique=False)
    op.create_index(op.f('ix_alerts_source'),     'alerts', ['source'],     unique=False)
    op.create_index(op.f('ix_alerts_is_read'),    'alerts', ['is_read'],    unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_read'),    table_name='alerts')
    op.drop_index(op.f('ix_alerts_source'),     table_name='alerts')
    op.drop_index(op.f('ix_alerts_level'),      table_name='alerts')
    op.drop_table('alerts')
